project:
  type: book

book:
  title: "Exploratory Data Analysis"
  author: "Rens Holmer"
  date: "7/15/2025"
  page-navigation: true
  search: true
  downloads: [pdf]
  repo-actions: [edit, issue]
  reader-mode: true
  license: CC-BY-NC 4.0
  sidebar:
    style: docked
  chapters:
    - index.qmd
    - part: week1/week1.qmd
      chapters: 
        - week1/summary_statistics.qmd
    - part: week2/week2.qmd
      chapters: 
        - week2/programming_concepts.qmd
        - week2/debugging.qmd
    - part: week3/week3.qmd
      chapters: 
        - week3/visualization.qmd
        - week3/unsupervised_analysis.qmd
    - part: week4/week4.qmd
      chapters: 
        - week4/regression_classification.qmd
        - week4/workflows.qmd
    - references.qmd

bibliography: references.bib
csl: nature.csl

format:
  html:
    theme:
      - pandoc
    font:
      google: "Noto Sans"
  pdf:
    documentclass: scrreprt
    papersize: letter
    highlight-style: github
    mainfont: "Noto Sans"
    engine: xelatex
    cite-method: biblatex



