project:
  type: book

book:
  title: "Exploratory Data Analysis"
  version: 0.1.0
  author: 
    - "Rens Holmer"
    - "Mark Sterken"
    - "Harm Nijveen"
    - "Peter Bourke"
  date: today
  page-navigation: true
  search: true
  downloads: [pdf]
  repo-actions: [edit, issue]
  reader-mode: true
  license: CC-BY-NC 4.0
  sidebar:
    style: docked
    tools:
      - icon: github
        href: "https://github.com/wur-bioinformatics/exploratory-data-analysis"
  chapters:
    - index.qmd
    - part: week1/week1.qmd
      chapters: 
        - week1/day1.qmd
        - week1/day2.qmd
    - part: week2/week2.qmd
      chapters: 
        - week2/summary_statistics_and_functions.qmd
        - week2/debugging_and_testing.qmd
        - week2/diving_into_the_tidyverse.qmd
    - part: week3/week3.qmd
      chapters: 
        - week3/day1.qmd
        - week3/visualization.qmd
        - week3/unsupervised_analysis.qmd
    - part: week4/week4.qmd
      chapters: 
        - week4/day1.qmd
    - part: appendices/appendices.qmd
      chapters:
        - appendices/base-r-cheatsheet.qmd
        - appendices/tidyverse-cheatsheet.qmd
        - appendices/ggplot-cheatsheet.qmd
        - appendices/datasets.qmd
        - appendices/qmd-notebooks-cheatsheet.qmd
    - references.qmd

bibliography: references.bib
csl: nature.csl

format:
  html:
    number-depth: 2
    theme:
      - pandoc
      - custom_styles.scss
    font:
      google: "Noto Sans"
    repo: "https://github.com/wur-bioinformatics/exploratory-data-analysis"
  pdf:
    documentclass: scrreprt
    papersize: letter
    highlight-style: github
    mainfont: "Noto Sans"
    engine: xelatex
    cite-method: biblatex



